import java.io.Serializable;

public class Run {
    public static void main(String[] args) {

    }
}

// Before java handle
public class Store<T extends Serializable> {
    private T object;
}


// After java handle
public class Store {
    private Serializable object;
}

// Bridge method
public class IntegerStack extends Stack {
    // Bridge method generated by the compiler
    
    public void push(Object value) {
        push((Integer)value);
    }

    public void push(Integer value) {
        super.push(value);
    }
}